# Generated by Django 5.2.3 on 2025-06-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('producers', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_year', models.CharField(blank=True, max_length=10)),
                ('films', models.ManyToManyField(related_name='characters', to='core.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='planets',
            field=models.ManyToManyField(related_name='films', to='core.planet'),
        ),
    ]
